# setup services 
version: '3'

services:
  django_server:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 url_shorten.wsgi:application

    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media  # Persist media files on the host machine
    restart: always
    depends_on:
      - url_shorten_db
      - url_shorten_redis

  url_shorten_redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"

  url_shorten_celery:
    build: .
    command: celery -A url_shorten worker --loglevel=info
    depends_on:
      - url_shorten_redis
    volumes:
      - ./media:/app/media  # Shared media storage
      - .:/app 
    restart: always
  
  url_shorten_celery_beat:
    build: .
    command: celery -A url_shorten beat --loglevel=info
    depends_on:
      - url_shorten_redis
      - url_shorten_celery
    volumes:
      - ./media:/app/media  # Shared media storage
      - .:/app 
    restart: always

  url_shorten_flower:
    build: .
    command: celery -A url_shorten flower --port=5555
    depends_on:
      - url_shorten_redis
      - url_shorten_celery
    ports:
      - "5555:5555"
    restart: always

  url_shorten_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shorten
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent PostgreSQL storage

  url_shorten_pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin    
    ports:
      - "5050:80"                              
    depends_on:
      - url_shorten_db

volumes:
  postgres_data:  # Persistent storage for PostgreSQL
  media_volume:   # Persistent storage for media files (mapped to host)
