# Generated by Django 5.1.6 on 2025-02-19 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_source', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_url', models.URLField()),
            ],
            options={
                'indexes': [models.Index(fields=['affiliate_source'], name='core_affili_affilia_6ef6de_idx'), models.Index(fields=['original_url'], name='core_affili_origina_b59d3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('short_url_key', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('original_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
