# Generated by Django 5.1.6 on 2025-02-19 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='affiliatesource',
            name='core_affili_origina_b59d3d_idx',
        ),
        migrations.RemoveField(
            model_name='affiliatesource',
            name='original_url',
        ),
        migrations.AddField(
            model_name='affiliatesource',
            name='url_shortener',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.urlshortener'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliatesource',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='affiliatesource',
            index=models.Index(fields=['url_shortener'], name='core_affili_url_sho_a07afa_idx'),
        ),
    ]
