# Generated by Django 5.1.6 on 2025-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_affiliatesource_core_affili_origina_b59d3d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url_key',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
