# Generated by Django 5.1.6 on 2025-02-19 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_urlshortener_short_url_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
